# metadata
run_name: 'map_wide'
# characteristic number for map
perf_num: 6

# map paths
map_path: './example_map'
map_ext: '.png'

# bottom left turn on map
# sx: -51.7536321 
# sy: -3.7800909
# stheta: -1.3702759732051

# start on the map
sx: 0.0
sy: 0.0
stheta: 1.3702759732051