# metadata
run_name: 'map_wide'
# characteristic number for map
perf_num: 6

# map paths
map_path: './example_map'
map_ext: '.png'

# top left turn on map
sx: -47.9104052
sy: 19.4375314
stheta: 4.97060422107126

# start on the map
# sx: 0.0
# sy: 0.0
# stheta: 1.3702759732051